var searchData=
[
  ['ai_5fgov_2ec',['AI_gov.c',['../AI__gov_8c.html',1,'']]],
  ['ai_5fgov_2eh',['AI_gov.h',['../AI__gov_8h.html',1,'']]],
  ['ai_5fgov_5fhardware_2ec',['AI_gov_hardware.c',['../AI__gov__hardware_8c.html',1,'']]],
  ['ai_5fgov_5fhardware_2eh',['AI_gov_hardware.h',['../AI__gov__hardware_8h.html',1,'']]],
  ['ai_5fgov_5fioctl_2ec',['AI_gov_ioctl.c',['../AI__gov__ioctl_8c.html',1,'']]],
  ['ai_5fgov_5fioctl_2eh',['AI_gov_ioctl.h',['../AI__gov__ioctl_8h.html',1,'']]],
  ['ai_5fgov_5fkernel_5fwrite_2eh',['AI_gov_kernel_write.h',['../AI__gov__kernel__write_8h.html',1,'']]],
  ['ai_5fgov_5fphases_2ec',['AI_gov_phases.c',['../AI__gov__phases_8c.html',1,'']]],
  ['ai_5fgov_5fphases_2eh',['AI_gov_phases.h',['../AI__gov__phases_8h.html',1,'']]],
  ['ai_5fgov_5fpower_5fmanager_2ec',['AI_gov_power_manager.c',['../AI__gov__power__manager_8c.html',1,'']]],
  ['ai_5fgov_5fpower_5fmanager_2eh',['AI_gov_power_manager.h',['../AI__gov__power__manager_8h.html',1,'']]],
  ['ai_5fgov_5fsched_2ec',['AI_gov_sched.c',['../AI__gov__sched_8c.html',1,'']]],
  ['ai_5fgov_5fsched_2eh',['AI_gov_sched.h',['../AI__gov__sched_8h.html',1,'']]],
  ['ai_5fgov_5fsysfs_2ec',['AI_gov_sysfs.c',['../AI__gov__sysfs_8c.html',1,'']]],
  ['ai_5fgov_5fsysfs_2eh',['AI_gov_sysfs.h',['../AI__gov__sysfs_8h.html',1,'']]],
  ['ai_5fgov_5ftask_5fhandling_2ec',['AI_gov_task_handling.c',['../AI__gov__task__handling_8c.html',1,'']]],
  ['ai_5fgov_5ftask_5fhandling_2eh',['AI_gov_task_handling.h',['../AI__gov__task__handling_8h.html',1,'']]],
  ['ai_5fgov_5ftypes_2eh',['AI_gov_types.h',['../AI__gov__types_8h.html',1,'']]],
  ['ai_5ftouch_5fnotifier_2ec',['AI_touch_notifier.c',['../AI__touch__notifier_8c.html',1,'']]],
  ['ai_5ftouch_5fnotifier_2eh',['AI_touch_notifier.h',['../AI__touch__notifier_8h.html',1,'']]]
];
